### ISSUE TITLE
스토리 스킵 버튼을 구현한다.

### ISSUE THREAD

**Issue by kth990303** [konkuk-galaxy/frontend#1]
## 구현사항
- 스토리를 생각해온다.
- 스킵 버튼을 구현한다.

**Comment by kth990303** [comment]
스토리는 우주 컨셉으로 갈게요~

~~
~~
~~

**Comment by KTIKTI** [comment]
22세기, 앞으로 일어나지 않을 것만 같았던 3차 세계대전은 지구를 황무지로 만드는데 충분하였습니다. 대전쟁 이후 인류는 단일 정부를 구성하는데 성공하였고 황폐해진 지구를 떠나 사람이 거주할 수 있는 새로운 행성을 찾는 것을 목표로 인류는 단합하였습니다.
그리고 시간은 2200년. 시대는 우주시대를 알렸고 인류의 첫 우주 탐사선인 뉴콜롬비아호는 다른 은하에 진입하는데 성공하였고 인류는 과학선과 더불어 과학선을 지휘할 과학자들을 고용하였습니다.
그리고 희소식이 들어왔습니다. 한 과학선이 탐사한 은하에 지구형 행성이 발견되었습니다. 지휘부는 그 소식에 기뻐하여 당장 그 행성에 우리 인류를 정착시키기로 결정을 내렸습니다.
허나 우주시대에 도달한 인류는 새로운 행성에 만족하지 않고 본격적으로 드넓은 우주를 탐사하기 시작하였습니다. 한 탐사선은 지구 출신이 아닌 외계 생명체를 만나는데 성공했습니다. 비록 지성이 없는 유기체이지만 훗날 지성과 문명을 가진 외계생명체를 만날 가능성은 급격히 높아져만 갔습니다. 인류는 외계생명체를 만날 것에 대비해, 강해져야함을 느꼈고, 알파은하에 당신을 탐사대장으로 고용하였습니다.
