### ISSUE TITLE
인게임 - 아이템(자원, 효과) 및 블록을 배치한다

### ISSUE THREAD

**Issue by kth990303** [konkuk-galaxy/frontend#5]
- 자바스크립트로 아이템 이미지 크기에 따라 적절히 배치한다
- 레벨(초급, 중급, 고급)에 따라 개수를 적절히 다르게 배치한다

**Comment by KTIKTI** [comment]
변수: stage

난이도
easy: stage 1부터 시작
normal: stage 21부터 시작
hard: stage 41부터 시작
*normal, hard의 경우 게임 오른쪽 화면에 스테이지 출력하거나 엔드화면에 스테이지 출력할 때 stage -20,-40을 하고 출력할 것

스테이지 완료할때마다 stage가 50이 될때까지 stage++

블록 개수: 15(stage 1) ~ 40(stage 50)
stage / 2 + 15
자원 개수: 14(stage 1) ~ 29(stage 50)
stage / 2 + 15 – (stage / 5 + 1)
벌칙 개수: 1(stage 1) ~ 11(stage 50)
stage / 5 + 1

**Comment by KTIKTI** [comment]
블록: 자원 / 공 추가 / 속도 변경 / 바 크기 변경 등
벌칙: 운석 / 지적 생명체

**Comment by KTIKTI** [comment]
자원:
미네랄 : 1
가스 : 2
DNA : 3
크리스탈 : 10
암흑물질 : 5
