### ISSUE TITLE
인게임 - 게임 기본요소를 구현한다

### ISSUE THREAD

**Issue by kth990303** [konkuk-galaxy/frontend#6]
- HTML 캔버스를 이용하여 기본적인 틀을 구현한다
  - 공을 발사하는 기능
  - 공이 블록에 맞았을 때 점수 계산 함수, 자원개수 증가 함수 등의 함수를 호출한다.
    -  함수를 구현할 필요는 없다.
  - 목숨 이미지 교체 등 간단한 작업을 수행한다.
  - 블록이 맞았을때 HIT = true를 반환한다. 
    - 벽돌이 부서질 필요는 없음

**Comment by asdfjklec** [comment]
close
